import { Router } from 'express';
import { categoriesRoutes } from './Categories.routes';
import { SpecificationsRoutes } from './Specifications.route';
import usersRoutes from './Users.route';
import authenticateRotes from './authenticate.route';
const router = Router();
router.use('/categories', categoriesRoutes);
router.use('/specifications', SpecificationsRoutes);
router.use('/users', usersRoutes);
router.use(authenticateRotes);
export { router };
